# .github/workflows/build_windows_v230_ready.yml
name: Build Windows v2.3.0 Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MSVC & Ninja
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}\vcpkg
            ${{ github.workspace }}\build\vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ github.sha }}

      - name: Install vcpkg deps (classic)
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          call vcpkg\bootstrap-vcpkg.bat
          call vcpkg\vcpkg install ^
            boost:x64-windows ^
            wxwidgets:x64-windows ^
            opencv4:x64-windows ^
            tbb:x64-windows ^
            glew:x64-windows ^
            glfw3:x64-windows ^
            eigen3:x64-windows ^
            nlopt:x64-windows ^
            zlib:x64-windows ^
            curl:x64-windows

      - name: Configure & Build
        run: >
          cmake -S . -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=x64-windows
          -DSLIC3R_STATIC=ON
          -DSLIC3R_GUI=ON
          -DSLIC3R_PCH=ON
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /Qp build\package\innosetup\orca_setup.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: OrcaSlicer_Windows_v2.3.0_installer
          path: build\package\OrcaSlicer*.exe
