name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [main, release/*]
    paths:
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'

env:
  BOOST_VERSION: "1.78.0"
  WINDOWS_SDK_VERSION: "10.0.18362.0"
  BOOST_SHA256: "8681f175d4bdb26c52222665793eef08490d7758529330f98d3b29dd0735bccc" # 1.78.0 的 SHA256

jobs:
  build_windows:
    name: Build Windows Installer
    runs-on: windows-latest
    timeout-minutes: 120  # 增加超时时间以容纳 Boost 编译

    steps:
      - name: Checkout v2.3.0
        uses: actions/checkout@v4
        with:
          repository: SoftFever/OrcaSlicer
          ref: v2.3.0
          path: orca-src

      - name: Install build tools
        run: |
          choco install -y ninja cmake git python --no-progress
          python -m pip install conan

      - name: Download and build Boost from source
        run: |
          # 设置路径变量
          $boostVersion = "$env:BOOST_VERSION".Replace('.', '_')
          $boostDir = "C:\local\boost_$boostVersion"
          $boostArchive = "boost_$boostVersion.zip"
          $url = "https://boostorg.jfrog.io/artifactory/main/release/$env:BOOST_VERSION/source/$boostArchive"
          
          # 下载 Boost 源代码
          Write-Host "Downloading Boost source from $url"
          Invoke-WebRequest -Uri $url -OutFile $boostArchive
          
          # 验证文件完整性
          $hash = (Get-FileHash -Path $boostArchive -Algorithm SHA256).Hash
          if ($hash -ne "$env:BOOST_SHA256") {
              Write-Error "Boost archive checksum mismatch! Expected $env:BOOST_SHA256, got $hash"
              exit 1
          }
          
          # 解压源代码
          Expand-Archive -Path $boostArchive -DestinationPath .
          
          # 重命名目录
          Rename-Item "boost_$boostVersion" "boost-src"
          
          # 配置和编译
          cd boost-src
          .\bootstrap.bat
          .\b2 install --prefix="$boostDir" --with-system --with-filesystem --with-program_options --with-thread --with-regex
          
          # 设置环境变量
          echo "BOOST_ROOT=$boostDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        env:
          BOOST_VERSION: ${{ env.BOOST_VERSION }}
          BOOST_SHA256: ${{ env.BOOST_SHA256 }}

      - name: Setup MSVC environment
        run: |
          $vsPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest `
            -products * `
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath
          
          $vcvarsPath = Join-Path $vsPath "VC\Auxiliary\Build\vcvars64.bat"
          
          # 设置环境变量
          cmd.exe /c "call `"$vcvarsPath`" && set > env_vars.txt"
          Get-Content env_vars.txt | ForEach-Object { 
            if ($_ -match "^(.*?)=(.*)$") { 
              Write-Output "$($matches[1])=$($matches[2])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            }
          }
          
          # 添加SDK版本
          echo "CMAKE_SYSTEM_VERSION=$env:WINDOWS_SDK_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure CMake
        working-directory: ./orca-src
        run: |
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_SYSTEM_VERSION=$env:CMAKE_SYSTEM_VERSION ^
            -DBOOST_ROOT="$env:BOOST_ROOT"

      - name: Build installer
        working-directory: ./orca-src
        run: cmake --build build --config Release --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrcaSlicer-Windows-Installer
          path: orca-src/build/*.exe
          retention-days: 7
